# Done to increase the memory available to the Gradle daemon.
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m

# Fabric Properties
# VERSION-INDEPENDENT: To upgrade to a newer Minecraft version, change:
# 1. minecraft_version
# 2. loader_version
# 3. fabric_version
# 4. yarn_mappings
minecraft_version=26.2
yarn_mappings=26.2+build.1
loader_version=0.19.3
fabric_version=0.155.2+26.2

# Mod Properties
mod_version=1.8.1
modmenu_version=20.0.1
maven_group=dev.fpsflow
archives_base_name=fpsflow

# Default Java target for single builds.
# Running `gradle clean build` will build the stable 1.21.11 target by default.
java_version=21
build_target=legacy
